name: Deploy DALLE-Backend
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t sblevinsdev/dalle_backend  .
      - name: Publish Image to docker hub
        run: docker push sblevinsdev/dalle_backend:latest
 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull sblevinsdev/dalle_backend:latest
      - name: Delete old container
        run: docker rm -f dalle-backend-container
      - name: Run Docker Container
        run: docker run -d -p 5555:5555 --name dalle-backend-container -e MONGODB_URL='${{ secrets.MONGODB_URL }}' sblevinsdev/dalle_backend