name: Deploy DALLE-Backend
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t sblevinsdev/dalle_backend  . (DockerHub Username/Repository Name . )
      - name: Publish Image to docker hub
        run: docker push sblevinsdev/dalle_backend:latest (DockerHub Username/Repository Name:latest )
 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull sblevinsdev/dalle_backend:latest (DockerHub Username/Repository Name:latest )
      - name: Delete old container
        run: docker rm -f dalle-backend-container (Old Container Name if any/New container Name)
      - name: Run Docker Container
        run: docker run -d -p 5555:5555(Configured Port:Configured Port) --name dalle-backend-container(New Container Name) -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' sblevinsdev/dalle_backend (DockerHub Username/Repository Name)